services:
  test_auth:
    build: .
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: postgres://postgres:onlyfortesting52528249@clair_postgres:5432/test?sslmode=disable
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: clair_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: onlyfortesting52528249
volumes:
  postgres_data:

